# Generated by Django 3.1.2 on 2022-05-14 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_companyinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
    ]
