# Generated by Django 3.1.2 on 2022-05-15 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_companyinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
    ]
