# Generated by Django 3.1.2 on 2022-05-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_site', '0006_delete_companyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(default='N/A', max_length=255)),
                ('price', models.FloatField()),
                ('price_earnings', models.FloatField()),
                ('dividend_yeild', models.FloatField()),
                ('earning_per_share', models.FloatField()),
                ('marker_cap', models.FloatField()),
                ('EBITDA', models.FloatField()),
                ('price_per_sales', models.FloatField()),
                ('price_per_book', models.FloatField()),
                ('link', models.CharField(max_length=255)),
            ],
        ),
    ]
